### ISSUE TITLE
Add ADS1115 I2C ADC 

### ISSUE THREAD

**Issue by kwonma** [OPEnSLab-OSU/Loom#24] opened 2019-10-15 22:50 UTC
Datasheet: https://cdn-learn.adafruit.com/downloads/pdf/adafruit-4-channel-adc-breakouts.pdf

Site: https://www.adafruit.com/product/1085

Requested during Chet's check in for Evaporometer.

**Comment by prototypicalpro** [comment] 2019-10-22 20:29
Duplicate of: https://github.com/OPEnSLab-OSU/Loom/issues/27

**Closed by prototypicalpro** 2019-10-22 20:29 UTC
Labels: Implementation Request, duplicate
